Feature/mood meter
jambit/Alor-Backend pull request #5
Opened 2019-11-18 15:54 UTC by ICE-H2O

2019-11-19 07:34 UTC, TobiasAnzinger approved these changes

2019-11-19 08:51 UTC, waspmuc requested changes
Great example why it is a bad idea to maintain multible branches...
You have the same changes here as in the other branch. Write small features and merge them regularly to master/develop and try to keep them atomic. You are working in a team and not on your own. Keep that in mind.

2019-11-19 09:37 UTC, waspmuc requested changes

2019-11-19 09:37 UTC, waspmuc commented on src/com/jambit/MoodMeter.java
> +@Path("/mdm")
there is no reason to abbreaviate that much. Readability and understandabilty is key for quality software. Try to use spelling and easy to understand names. I absolutely recommend that book for you: https://www.investigatii.md/uploads/resurse/Clean_Code.pdf

2019-11-19 09:37 UTC, waspmuc commented on src/com/jambit/MoodMeter.java
> +  @Path("dist")
use proper name

2019-11-19 09:37 UTC, waspmuc commented on src/com/jambit/MoodMeter.java
> +    return Response.status(200).entity(time).build();
why do you return the parameter? 
You should call the service layer instead and return a proper datatype. E.g. 
moodMeterService.fetchEntriesInTime(Date time)...
The implementation of that service method could then return a not implemented exception or any empty list until you're done.

2019-11-19 09:37 UTC, waspmuc commented on src/com/jambit/MoodMeter.java
> +  public Response getAvg(@DefaultValue("4") @QueryParam("t") String time) {
you also need to handle/parse the time

2019-11-21 08:31 UTC, ICE-H2O commented on src/com/jambit/MoodMeter.java
> +  @Path("dist")
is distro okay ?

2019-11-25 07:38 UTC, ICE-H2O commented on src/com/jambit/services/MoodMeterService.java
> +            entrySumm = entrySumm + moodEntries.get(i).vote;
Use x += y instead if x = x + y

2019-11-25 07:38 UTC, ICE-H2O commented on src/com/jambit/services/MoodMeterService.java
> +        return average;
You can combine both lines

2019-12-03 18:03 UTC, waspmuc approved these changes
lass uns das mal mache ;)

2019-12-03 18:03 UTC, merged