removed *jar from gitignore
jambit/Alor-Backend pull request #6
Opened 2019-11-26 13:51 UTC by TobiasAnzinger

removed *jar from gitignore
add gradle-wrapper.jar

2019-11-26 15:27 UTC, iceHtwoO approved these changes

2019-11-26 16:05 UTC, waspmuc requested changes

2019-11-26 16:05 UTC, waspmuc commented on src/main/com/jambit/RestAPI.java
> -}
Why did you touch this file?

2019-11-27 14:29 UTC, waspmuc approved these changes

2019-11-27 14:36 UTC, merged